FROM kalilinux/kali-rolling

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    #kali-linux-default \
    net-tools iproute2 iputils-ping dnsutils \
    vim nano curl wget git zsh openssh-server \
    && apt clean

# Copia e prepara o script de gerenciamento de rede
COPY switch_net.sh /usr/local/bin/switch_net.sh
RUN chmod +x /usr/local/bin/switch_net.sh

# Copia e prepara o script de entrypoint
COPY entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["/bin/zsh"]
